image: zeroonetechnology/geni:latest

test:
  stage: test
  script:
    - lein midje
  only:
    - develop
    - merge_requests

linters:
  stage: test
  script:
    - clj-kondo --lint src test
  only:
    - develop
    - merge_requests

# Source: https://gitlab.com/gitlab-org/gitlab-runner/issues/3559
coverage:
  stage: test
  script:
    - lein cloverage --fail-threshold 90 --ns-exclude-regex zero-one.fxl.specs | perl -pe 's/\e\[?.*?[\@-~]//g'
  coverage: /ALL\sFILES.*?\s+(\d+.\d+)/
  only:
    - develop
    - merge_requests
